apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: load-demo-ui
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: load-demo-ui
        version: "1"
        role: ui
    spec:
      containers:
      - name: load-demo-ui
        image: jhgaylor/k8s-load-demo-ui:latest
        ports:
        - containerPort: 8080
